#line 1 "probeconfscan.c"

#line 3 "probeconfscan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer probeconfscan__create_buffer
#define yy_delete_buffer probeconfscan__delete_buffer
#define yy_scan_buffer probeconfscan__scan_buffer
#define yy_scan_string probeconfscan__scan_string
#define yy_scan_bytes probeconfscan__scan_bytes
#define yy_init_buffer probeconfscan__init_buffer
#define yy_flush_buffer probeconfscan__flush_buffer
#define yy_load_buffer_state probeconfscan__load_buffer_state
#define yy_switch_to_buffer probeconfscan__switch_to_buffer
#define yypush_buffer_state probeconfscan_push_buffer_state
#define yypop_buffer_state probeconfscan_pop_buffer_state
#define yyensure_buffer_stack probeconfscan_ensure_buffer_stack
#define yy_flex_debug probeconfscan__flex_debug
#define yyin probeconfscan_in
#define yyleng probeconfscan_leng
#define yylex probeconfscan_lex
#define yylineno probeconfscan_lineno
#define yyout probeconfscan_out
#define yyrestart probeconfscan_restart
#define yytext probeconfscan_text
#define yywrap probeconfscan_wrap
#define yyalloc probeconfscan_alloc
#define yyrealloc probeconfscan_realloc
#define yyfree probeconfscan_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define probeconfscan__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer probeconfscan__create_buffer
#endif

#ifdef yy_delete_buffer
#define probeconfscan__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer probeconfscan__delete_buffer
#endif

#ifdef yy_scan_buffer
#define probeconfscan__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer probeconfscan__scan_buffer
#endif

#ifdef yy_scan_string
#define probeconfscan__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string probeconfscan__scan_string
#endif

#ifdef yy_scan_bytes
#define probeconfscan__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes probeconfscan__scan_bytes
#endif

#ifdef yy_init_buffer
#define probeconfscan__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer probeconfscan__init_buffer
#endif

#ifdef yy_flush_buffer
#define probeconfscan__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer probeconfscan__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define probeconfscan__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state probeconfscan__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define probeconfscan__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer probeconfscan__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define probeconfscan_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state probeconfscan_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define probeconfscan_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state probeconfscan_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define probeconfscan_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack probeconfscan_ensure_buffer_stack
#endif

#ifdef yylex
#define probeconfscan_lex_ALREADY_DEFINED
#else
#define yylex probeconfscan_lex
#endif

#ifdef yyrestart
#define probeconfscan_restart_ALREADY_DEFINED
#else
#define yyrestart probeconfscan_restart
#endif

#ifdef yylex_init
#define probeconfscan_lex_init_ALREADY_DEFINED
#else
#define yylex_init probeconfscan_lex_init
#endif

#ifdef yylex_init_extra
#define probeconfscan_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra probeconfscan_lex_init_extra
#endif

#ifdef yylex_destroy
#define probeconfscan_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy probeconfscan_lex_destroy
#endif

#ifdef yyget_debug
#define probeconfscan_get_debug_ALREADY_DEFINED
#else
#define yyget_debug probeconfscan_get_debug
#endif

#ifdef yyset_debug
#define probeconfscan_set_debug_ALREADY_DEFINED
#else
#define yyset_debug probeconfscan_set_debug
#endif

#ifdef yyget_extra
#define probeconfscan_get_extra_ALREADY_DEFINED
#else
#define yyget_extra probeconfscan_get_extra
#endif

#ifdef yyset_extra
#define probeconfscan_set_extra_ALREADY_DEFINED
#else
#define yyset_extra probeconfscan_set_extra
#endif

#ifdef yyget_in
#define probeconfscan_get_in_ALREADY_DEFINED
#else
#define yyget_in probeconfscan_get_in
#endif

#ifdef yyset_in
#define probeconfscan_set_in_ALREADY_DEFINED
#else
#define yyset_in probeconfscan_set_in
#endif

#ifdef yyget_out
#define probeconfscan_get_out_ALREADY_DEFINED
#else
#define yyget_out probeconfscan_get_out
#endif

#ifdef yyset_out
#define probeconfscan_set_out_ALREADY_DEFINED
#else
#define yyset_out probeconfscan_set_out
#endif

#ifdef yyget_leng
#define probeconfscan_get_leng_ALREADY_DEFINED
#else
#define yyget_leng probeconfscan_get_leng
#endif

#ifdef yyget_text
#define probeconfscan_get_text_ALREADY_DEFINED
#else
#define yyget_text probeconfscan_get_text
#endif

#ifdef yyget_lineno
#define probeconfscan_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno probeconfscan_get_lineno
#endif

#ifdef yyset_lineno
#define probeconfscan_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno probeconfscan_set_lineno
#endif

#ifdef yywrap
#define probeconfscan_wrap_ALREADY_DEFINED
#else
#define yywrap probeconfscan_wrap
#endif

#ifdef yyalloc
#define probeconfscan_alloc_ALREADY_DEFINED
#else
#define yyalloc probeconfscan_alloc
#endif

#ifdef yyrealloc
#define probeconfscan_realloc_ALREADY_DEFINED
#else
#define yyrealloc probeconfscan_realloc
#endif

#ifdef yyfree
#define probeconfscan_free_ALREADY_DEFINED
#else
#define yyfree probeconfscan_free
#endif

#ifdef yytext
#define probeconfscan_text_ALREADY_DEFINED
#else
#define yytext probeconfscan_text
#endif

#ifdef yyleng
#define probeconfscan_leng_ALREADY_DEFINED
#else
#define yyleng probeconfscan_leng
#endif

#ifdef yyin
#define probeconfscan_in_ALREADY_DEFINED
#else
#define yyin probeconfscan_in
#endif

#ifdef yyout
#define probeconfscan_out_ALREADY_DEFINED
#else
#define yyout probeconfscan_out
#endif

#ifdef yy_flex_debug
#define probeconfscan__flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug probeconfscan__flex_debug
#endif

#ifdef yylineno
#define probeconfscan_lineno_ALREADY_DEFINED
#else
#define yylineno probeconfscan_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[479] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   74,   37,    3,    6,
       37,    4,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   55,    3,   50,   52,   53,    5,   54,   52,
       49,    3,   73,   49,   49,   49,   57,    3,   56,   57,
        3,   58,   72,    3,   64,   63,   73,    2,    2,    1,
        2,    3,   61,   62,   73,   62,   62,    3,    6,    4,
        0,    0,    4,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        3,   50,    5,   52,    5,    5,   52,    3,    0,    0,

        0,   57,    3,   57,   56,   57,   57,    3,   58,   72,
        3,   71,   70,   68,   69,   65,   67,   66,    3,    1,
        0,    0,    0,    3,   61,    0,   62,    0,    0,   62,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   52,    0,    0,    0,   62,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   52,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   16,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   31,    0,    0,    0,    0,    0,
       52,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   22,   23,
        0,    0,    0,    0,    0,   33,    0,   36,    0,   52,
        0,    0,    0,    0,    0,    0,    0,    9,    0,    0,
        0,    0,    0,    0,    0,   17,    0,    0,   23,    0,
        0,    0,    0,    0,    0,    0,   52,    0,    0,    0,
        0,    0,    0,    0,    0,    9,   10,    0,    0,    0,
        0,    0,    0,    0,    0,   21,    0,    0,    0,    0,
       30,   32,    0,    0,   52,    0,    0,    0,    0,    0,

        0,    0,    8,    0,    0,    0,    0,   13,   14,    0,
        0,    0,    0,    0,    0,   28,    0,    0,    0,   51,
        0,    0,   46,    0,    0,    0,    0,    0,    8,    0,
        0,    0,    0,   15,    0,    0,   18,    0,    0,   18,
        0,   19,    0,    0,    0,    0,    0,    0,    0,   46,
        0,    0,    0,    0,   60,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   43,    0,
        0,    0,    0,    0,   59,    0,    7,    0,    0,    0,
       39,    0,    0,    0,    0,    0,    0,    0,    0,   43,
        0,    0,    0,   48,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   40,    0,    0,    0,
       48,    0,    0,   38,    0,   24,   25,    0,   29,   34,
       35,   40,    0,    0,    0,   45,    0,    0,    0,    0,
        0,    0,    0,    0,   45,   11,    0,   20,    0,    0,
        0,    0,    0,   42,    0,    0,    0,    0,    0,   47,
       42,    0,    0,    0,    0,    0,   47,   12,    0,    0,
        0,   44,    0,    0,    0,   44,    0,   27,   41,    0,
       41,    0,    0,    0,    0,    0,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    4,    4,    4,    1,    4,
        4,    4,    4,    7,    8,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    9,    4,    4,    4,    4,   10,   11,   12,   13,

       14,   15,   16,   17,   18,    4,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[34] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    3,    5,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static const flex_int16_t yy_base[501] =
    {   0,
        0,    0,   33,   59,   84,  110,  137,  144,  151,  158,
       39,   44,   48,   65,  165,  179,  943,  944,   67,  944,
      934,   53,   64,   66,   35,   37,   69,   80,   81,   29,
       67,   87,  944,   76,  944,    0,  944,   97,  944,  927,
      944,  938,  944,  917,  924,  914,    0,  103,    0,  112,
      114,  944,    0,  934,  944,  944,  191,  944,  116,  944,
      122,  124,  944,    0,  126,  944,  913,  129,  944,  131,
      926,   84,  171,  173,  175,  128,  161,  182,  154,  184,
      189,  181,  183,  191,  195,  200,  193,  212,  206,  196,
      224,  944,  229,    0,  231,  233,  912,  930,  898,  903,

      900,    0,  235,  237,    0,  240,  242,  244,  944,    0,
      926,  944,  944,  944,  944,  944,  944,  944,  246,  944,
      248,  251,  253,  255,  944,  257,    0,  260,  262,  914,
      258,  259,  260,  113,  261,  268,  263,  201,  264,  267,
      269,  918,  170,  917,  271,  273,  278,  276,  216,  280,
      282,  914,  915,  894,  895,  918,  285,  287,  286,  291,
      292,  293,  295,  296,  297,  304,  308,  309,  310,  313,
      317,  911,  316,  315,  325,  328,  910,  330,  331,  899,
      898,  897,  902,  338,  336,  337,  338,  343,  341,  348,
      347,  887,  886,  897,  902,  350,   75,  352,  351,  353,

      354,  359,  372,  363,  901,  360,  366,  374,  358,  380,
      886,  373,  885,  892,  891,  375,  379,  378,  391,  896,
      399,  395,  880,  879,  879,  396,  403,  404,  892,  406,
      891,  408,  407,  392,  411,  890,  413,  889,  888,  882,
      866,  411,  883,  884,  869,  416,  418,  419,  420,  427,
      421,  882,  860,  877,  860,  435,  424,  432,  436,  452,
      440,  445,  433,  444,  446,  450,  872,  871,  864,  869,
      854,  863,  853,  447,  459,  871,  870,  453,  455,  472,
      853,  862,  852,  872,  469,  865,  457,  473,  477,  474,
      864,  863,  478,  479,  844,  843,  845,  839,  848,  467,

      842,  486,  484,  489,  492,  494,  497,  944,  944,  838,
      504,  515,  500,  855,  854,  853,  501,  852,  502,    0,
      844,  846,  830,  833,  827,  508,  828,  514,  845,  513,
      515,  516,  517,  944,  530,  536,  944,  538,  540,  544,
      536,  844,  540,  541,  543,  554,  521,  841,  831,  944,
      827,  834,  827,  832,  571,  548,  837,  836,  547,  545,
      571,  560,  568,  574,  572,  579,  576,  831,  815,  833,
      814,  816,  810,  583,  944,  590,  829,  590,  582,  593,
      828,  595,  594,  597,  601,  602,  604,  603,  821,  944,
      816,  818,  820,  804,  614,  623,  610,  622,  605,  614,

      619,  623,  518,  555,  626,  627,  803,  615,  819,  809,
      944,  630,  633,  819,  634,  818,  817,  816,  815,  814,
      797,  944,  767,  633,  770,  745,  637,  641,  642,  665,
      753,  739,  737,  704,  944,  709,  644,  708,  645,  647,
      689,  691,  685,  685,  648,  650,  651,  696,  698,  682,
      944,  656,  669,  668,  698,  688,  944,  697,  672,  674,
      690,  674,  673,  658,  648,  944,  646,  383,  121,  676,
      944,  683,  685,  677,  690,  691,   44,  944,  719,  724,
      729,  734,  739,  744,  747,  752,  755,  760,  765,  770,
      775,  780,  783,  788,  791,  796,  801,  806,  811,  816

    } ;

static const flex_int16_t yy_def[501] =
    {   0,
      478,    1,  479,  479,  480,  480,  481,  481,  481,  481,
      482,  482,  483,  483,  484,  484,  478,  478,  478,  478,
      485,  486,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  478,  478,  478,  487,  478,  488,  478,  487,
      478,  478,  478,  478,  478,  478,  489,  489,  490,  491,
      489,  478,  492,  492,  478,  478,  493,  478,  478,  478,
      494,  478,  478,  495,  496,  478,  495,  478,  478,  486,
      485,  485,  486,  486,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      478,  478,  488,  487,  488,  488,  487,  478,  478,  478,

      478,  489,  489,  491,  490,  491,  491,  489,  478,  492,
      492,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      494,  494,  494,  478,  478,  496,  495,  496,  496,  495,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  487,  478,  478,  478,  495,  485,  485,  485,  485,
      485,  485,  478,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  487,
      478,  478,  478,  478,  485,  485,  485,  485,  485,  485,
      485,  478,  478,  478,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      487,  478,  478,  478,  478,  485,  485,  485,  485,  485,
      485,  485,  478,  478,  478,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  487,
      478,  478,  478,  478,  478,  485,  485,  485,  485,  485,
      485,  485,  478,  478,  478,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  487,  478,  478,  478,
      478,  478,  478,  485,  485,  485,  485,  485,  485,  485,
      478,  478,  478,  497,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  487,  478,  478,  478,  478,  478,

      478,  485,  485,  485,  485,  485,  485,  478,  478,  478,
      498,  499,  485,  485,  485,  485,  485,  485,  485,  487,
      478,  478,  478,  478,  478,  478,  478,  485,  485,  485,
      485,  485,  485,  478,  498,  498,  478,  498,  499,  498,
      485,  485,  485,  485,  485,  485,  485,  478,  478,  478,
      478,  478,  478,  478,  478,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  478,  478,  478,
      478,  478,  478,  478,  478,  500,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  478,  478,
      478,  478,  478,  478,  500,  500,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  478,  478,  478,  478,
      478,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  478,  478,  478,  478,  478,  485,  485,  485,  485,
      478,  478,  478,  478,  478,  485,  485,  485,  485,  485,
      478,  478,  478,  478,  485,  485,  485,  478,  478,  478,
      478,  485,  485,  485,  478,  478,  478,  485,  485,  485,
      478,  478,  485,  485,  478,  478,  485,  485,  478,  485,
      478,  485,  485,  485,  485,  485,  485,    0,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478

    } ;

static const flex_int16_t yy_nxt[978] =
    {   0,
       18,   19,   20,   21,   18,   22,   18,   21,   21,   23,
       21,   21,   24,   25,   21,   26,   21,   27,   21,   28,
       21,   21,   21,   29,   30,   31,   32,   21,   21,   21,
       21,   21,   21,   33,   34,   35,   72,   37,   38,   39,
       54,   55,   72,   56,   72,   54,   55,   57,   56,   59,
       60,   72,   57,   61,   74,   69,   78,   87,   40,   33,
       34,   35,   79,   37,   38,   39,   59,   60,   68,   69,
       61,   72,   70,   72,   72,   75,   72,   91,   92,   76,
       88,   93,   72,   77,   40,   42,   43,   72,   72,  227,
       80,   72,   81,   44,   72,   82,   45,   83,   96,   92,

       89,  131,   84,   85,  103,   69,   86,  132,  104,   90,
       46,   42,   43,  107,   69,  108,  109,  119,  120,   44,
       72,  121,   45,  123,  120,  124,  125,  129,  125,  126,
       68,   69,   74,   69,   70,   72,   46,   47,   48,   20,
      161,   47,   50,   47,   47,   48,   20,  471,   47,   50,
       47,   47,   51,   52,  134,   47,   47,   47,   47,   51,
       52,   72,   47,   47,   47,   43,   62,   63,   72,   43,
       65,   66,   74,   69,   74,   69,  137,   72,   67,   43,
       62,   63,   72,   43,   65,   66,  133,  135,   72,   72,
       72,   72,   67,  113,  136,  138,   72,  170,   72,  140,

       72,  114,   72,   72,  142,  115,  144,   72,   72,  143,
      148,  139,  116,   72,  145,  141,  117,  146,  118,   72,
      165,  149,  147,   72,  151,   91,   92,  150,  177,   93,
       96,   92,   96,   92,   96,   92,  103,   69,  107,   69,
      104,  107,   69,  107,   69,  108,  109,  119,  120,  123,
      120,  121,  123,  120,  123,  120,  124,  125,  129,  125,
      126,  129,  125,  129,  125,   72,   72,   72,   72,  163,
       72,   72,  162,  160,   72,   72,   72,  166,   72,  157,
       72,  158,  168,   72,  159,   72,  167,   72,  174,   72,
      172,  164,   72,   72,   72,  173,  163,  186,   72,   72,

       72,  176,  191,   72,   72,  175,  178,  179,  188,  190,
      192,   72,  185,  187,  189,   72,   72,   72,  193,  195,
       72,  194,   72,   72,   72,  196,  201,  200,  205,  197,
      198,  202,   72,  132,  131,   72,  199,   72,   72,  184,
      132,  204,  210,   72,   72,   72,  207,  206,   72,  216,
       72,  218,  209,  219,   72,   72,  217,   72,   72,   72,
       72,   72,  226,  228,  215,   72,   72,   72,  220,  221,
       72,  235,  222,   72,  157,  231,  230,  229,  232,   72,
      234,   72,   72,  238,  233,   72,   72,   72,  237,  131,
       72,  131,  236,  239,  241,  132,  242,  132,   72,   72,

      246,  247,   72,   72,  249,  248,   72,  252,  251,  256,
       72,   72,  257,   72,   72,   72,  186,  261,   72,  263,
       72,  269,  258,   72,  262,   72,   72,   72,   72,  275,
      274,   72,  259,  264,   72,  285,  284,  270,  265,   72,
       72,  278,   72,   72,  131,  276,  277,   72,  279,  218,
      132,   72,   72,   72,   72,  289,  302,   72,  286,   72,
       72,  287,   72,  292,   72,  291,   72,  131,  293,  131,
      290,  294,  305,  132,  288,  132,   72,  303,  304,   72,
       72,   72,  313,  314,   72,   72,   72,  317,  325,  131,
      326,   72,  319,   72,  315,  132,   72,  328,  318,   72,

      306,   72,  307,  316,   72,  336,  337,  341,   72,   72,
      329,  330,  345,  333,  331,  332,  339,  340,  353,  335,
       72,   72,   72,   72,   72,   72,  342,  356,   72,  347,
      360,  336,  337,  357,  354,  359,  358,  336,  337,  336,
      337,  339,  340,   72,  335,  336,  337,   72,   72,  418,
       72,  367,   72,  131,   72,   72,  362,  131,  131,  132,
      380,   72,   72,  132,  363,  361,  381,   72,  366,  364,
      365,  131,  374,  375,  377,   72,  376,  132,   72,   72,
      382,   72,  383,   72,  374,  375,   72,  419,  376,   72,
      384,  396,  375,  159,  386,  385,  387,   72,  388,  131,

       72,   72,   72,  398,   72,  132,  397,  131,   72,   72,
       72,   72,   72,  132,  400,  396,  375,   72,  403,  399,
      401,   72,  402,  405,  396,  375,   72,  404,  406,   72,
       72,  414,  412,   72,   72,  413,  423,   72,  424,  420,
       72,   72,  415,  432,   72,  421,  416,  429,   72,   72,
      417,   72,   72,  470,   72,   72,  427,   72,   72,  433,
      428,  469,  454,   72,  436,   72,  445,  446,  438,  447,
      453,  437,   72,  452,  458,   72,   72,  439,  459,   72,
       72,   72,  131,   72,   72,  468,  460,  464,  132,  463,
       72,  440,   72,  131,  467,  475,  474,   72,   72,  132,

      466,  465,  472,  476,   72,  473,  462,  461,  457,  456,
      455,  451,  450,  449,  448,   72,   72,  444,  477,   36,
       36,   36,   36,   36,   41,   41,   41,   41,   41,   49,
       49,   49,   49,   49,   53,   53,   53,   53,   53,   58,
       58,   58,   58,   58,   64,   64,   64,   64,   64,   71,
      443,   71,   73,   73,   73,   73,   73,   94,  442,   94,
       95,   95,   95,   95,   95,  102,  441,  102,  102,  102,
      105,  435,  105,  105,  105,  106,  106,  106,  106,  106,
      110,  434,  110,  112,  112,  112,  112,  112,  122,  122,
      122,  122,  122,  127,  431,  127,  128,  128,  128,  128,

      128,  311,  311,  311,   72,  311,  335,  335,  335,  335,
      335,  338,  338,  338,  338,  338,  395,  395,  395,  395,
      395,   72,   72,  430,   72,   72,   72,  426,  425,  422,
      411,  410,  409,  408,  407,   72,   72,  394,  393,  392,
      391,  390,  389,  379,  378,  373,  372,  371,  370,  369,
      368,   72,   72,  355,  352,  351,  350,  349,  348,  346,
       72,  344,  343,  334,  327,  324,  323,  322,  321,  320,
       72,   72,   72,  312,  310,  309,  308,   72,   72,  301,
      300,  299,  298,  297,  296,  295,  283,  282,  281,  280,
      273,  272,  271,  268,  267,  266,   72,   72,  260,   72,

      255,  254,  253,  250,  245,  244,  243,  240,   72,   72,
      225,  224,  223,  214,  213,  212,  211,  208,  203,  184,
      183,  182,  181,  180,  171,  169,  156,  111,  155,  154,
      153,   98,  152,   72,  130,  111,  101,  100,   99,   98,
       97,   72,  478,   17,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478
    } ;

static const flex_int16_t yy_chk[978] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,   30,    3,    3,    3,
       11,   11,   25,   11,   26,   12,   12,   11,   12,   13,
       13,  477,   12,   13,   22,   22,   25,   30,    3,    4,
        4,    4,   26,    4,    4,    4,   14,   14,   19,   19,
       14,   23,   19,   24,   31,   23,   27,   34,   34,   24,
       31,   34,  197,   24,    4,    5,    5,   28,   29,  197,
       27,   72,   27,    5,   32,   27,    5,   28,   38,   38,

       32,   72,   28,   29,   48,   48,   29,   72,   48,   32,
        5,    6,    6,   50,   50,   51,   51,   59,   59,    6,
      134,   59,    6,   61,   61,   62,   62,   65,   65,   62,
       68,   68,   70,   70,   68,   76,    6,    7,    7,    7,
      134,    7,    7,    7,    8,    8,    8,  469,    8,    8,
        8,    9,    9,    9,   76,    9,    9,    9,   10,   10,
       10,   79,   10,   10,   10,   15,   15,   15,   77,   15,
       15,   15,   73,   73,   74,   74,   79,  143,   15,   16,
       16,   16,   75,   16,   16,   16,   75,   77,   82,   78,
       83,   80,   16,   57,   78,   80,   81,  143,   84,   81,

       87,   57,   85,   90,   82,   57,   84,   86,  138,   83,
       87,   80,   57,   89,   85,   81,   57,   86,   57,   88,
      138,   88,   86,  149,   90,   91,   91,   89,  149,   91,
       93,   93,   95,   95,   96,   96,  103,  103,  104,  104,
      103,  106,  106,  107,  107,  108,  108,  119,  119,  121,
      121,  119,  122,  122,  123,  123,  124,  124,  126,  126,
      124,  128,  128,  129,  129,  131,  132,  133,  135,  136,
      137,  139,  135,  133,  140,  136,  141,  139,  145,  131,
      146,  131,  141,  148,  132,  147,  140,  150,  147,  151,
      145,  137,  157,  159,  158,  146,  163,  158,  160,  161,

      162,  148,  162,  164,  165,  147,  150,  151,  159,  161,
      163,  166,  157,  158,  160,  167,  168,  169,  163,  164,
      170,  163,  174,  173,  171,  165,  170,  169,  174,  166,
      167,  171,  175,  169,  171,  176,  168,  178,  179,  184,
      171,  173,  179,  185,  186,  187,  176,  175,  189,  185,
      188,  187,  178,  188,  191,  190,  186,  196,  199,  198,
      200,  201,  196,  198,  184,  209,  202,  206,  189,  190,
      204,  206,  191,  207,  200,  201,  200,  199,  202,  203,
      204,  208,  216,  209,  203,  218,  217,  210,  208,  203,
      468,  208,  207,  210,  212,  203,  212,  208,  219,  234,

      216,  217,  222,  226,  219,  218,  221,  222,  221,  226,
      227,  228,  227,  230,  233,  232,  230,  232,  235,  234,
      237,  242,  228,  246,  233,  247,  248,  249,  251,  247,
      246,  257,  230,  235,  250,  257,  256,  242,  237,  258,
      263,  250,  256,  259,  250,  248,  249,  261,  251,  259,
      250,  264,  262,  265,  274,  261,  274,  266,  258,  260,
      278,  260,  279,  264,  287,  263,  275,  266,  265,  260,
      262,  266,  279,  266,  260,  260,  285,  275,  278,  280,
      288,  290,  285,  287,  289,  293,  294,  290,  300,  280,
      300,  303,  294,  302,  288,  280,  304,  302,  293,  305,

      280,  306,  280,  289,  307,  311,  311,  313,  317,  319,
      303,  304,  317,  307,  305,  306,  312,  312,  326,  312,
      330,  328,  331,  332,  333,  403,  313,  328,  347,  319,
      333,  335,  335,  330,  326,  332,  331,  336,  336,  338,
      338,  339,  339,  341,  339,  340,  340,  343,  344,  403,
      345,  347,  360,  341,  359,  356,  343,  343,  344,  341,
      359,  346,  404,  343,  344,  341,  360,  362,  346,  344,
      345,  346,  355,  355,  356,  363,  355,  346,  361,  365,
      361,  364,  362,  367,  374,  374,  366,  404,  374,  379,
      363,  376,  376,  363,  365,  364,  366,  378,  367,  379,

      380,  383,  382,  379,  384,  379,  378,  378,  385,  386,
      388,  387,  399,  378,  382,  395,  395,  397,  385,  380,
      383,  400,  384,  387,  396,  396,  401,  386,  388,  398,
      402,  399,  397,  405,  406,  398,  408,  412,  408,  405,
      413,  415,  400,  424,  427,  406,  401,  415,  428,  429,
      402,  437,  439,  467,  440,  445,  412,  446,  447,  424,
      413,  465,  447,  452,  427,  464,  437,  439,  429,  440,
      446,  428,  430,  445,  452,  454,  453,  430,  453,  459,
      463,  460,  430,  470,  474,  464,  454,  460,  430,  459,
      472,  430,  473,  470,  463,  474,  473,  475,  476,  470,

      462,  461,  470,  475,  458,  472,  456,  455,  450,  449,
      448,  444,  443,  442,  441,  438,  436,  434,  476,  479,
      479,  479,  479,  479,  480,  480,  480,  480,  480,  481,
      481,  481,  481,  481,  482,  482,  482,  482,  482,  483,
      483,  483,  483,  483,  484,  484,  484,  484,  484,  485,
      433,  485,  486,  486,  486,  486,  486,  487,  432,  487,
      488,  488,  488,  488,  488,  489,  431,  489,  489,  489,
      490,  426,  490,  490,  490,  491,  491,  491,  491,  491,
      492,  425,  492,  493,  493,  493,  493,  493,  494,  494,
      494,  494,  494,  495,  423,  495,  496,  496,  496,  496,

      496,  497,  497,  497,  421,  497,  498,  498,  498,  498,
      498,  499,  499,  499,  499,  499,  500,  500,  500,  500,
      500,  420,  419,  418,  417,  416,  414,  410,  409,  407,
      394,  393,  392,  391,  389,  381,  377,  373,  372,  371,
      370,  369,  368,  358,  357,  354,  353,  352,  351,  349,
      348,  342,  329,  327,  325,  324,  323,  322,  321,  318,
      316,  315,  314,  310,  301,  299,  298,  297,  296,  295,
      292,  291,  286,  284,  283,  282,  281,  277,  276,  273,
      272,  271,  270,  269,  268,  267,  255,  254,  253,  252,
      245,  244,  243,  241,  240,  239,  238,  236,  231,  229,

      225,  224,  223,  220,  215,  214,  213,  211,  205,  195,
      194,  193,  192,  183,  182,  181,  180,  177,  172,  156,
      155,  154,  153,  152,  144,  142,  130,  111,  101,  100,
       99,   98,   97,   71,   67,   54,   46,   45,   44,   42,
       40,   21,   17,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "probeconfscan.l"
#line 2 "probeconfscan.l"
/*
** Copyright (C) 2005-2023 by Carnegie Mellon University.
**
** @OPENSOURCE_LICENSE_START@
**
** SiLK 3.22.0
**
** Copyright 2023 Carnegie Mellon University.
**
** NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
** INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
** UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED,
** AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR
** PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF
** THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF
** ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT
** INFRINGEMENT.
**
** Released under a GNU GPL 2.0-style license, please see LICENSE.txt or
** contact permission@sei.cmu.edu for full terms.
**
** [DISTRIBUTION STATEMENT A] This material has been approved for public
** release and unlimited distribution.  Please see Copyright notice for
** non-US Government use and distribution.
**
** GOVERNMENT PURPOSE RIGHTS - Software and Software Documentation
**
** Contract No.: FA8702-15-D-0002
** Contractor Name: Carnegie Mellon University
** Contractor Address: 4500 Fifth Avenue, Pittsburgh, PA 15213
**
** The Government's rights to use, modify, reproduce, release, perform,
** display, or disclose this software are restricted by paragraph (b)(2) of
** the Rights in Noncommercial Computer Software and Noncommercial Computer
** Software Documentation clause contained in the above identified
** contract. No restrictions apply after the expiration date shown
** above. Any reproduction of the software or portions thereof marked with
** this legend must also reproduce the markings.
**
** Carnegie Mellon(R) and CERT(R) are registered in the U.S. Patent and
** Trademark Office by Carnegie Mellon University.
**
** This Software includes and/or makes use of Third-Party Software each
** subject to its own license.
**
** DM23-0973
**
** @OPENSOURCE_LICENSE_END@
*/

/*
**  Tokenizer for probe configuration file.
**
*/

#include <silk/silk.h>

RCSIDENT("$SiLK: probeconfscan.l 05d39531ae59 2023-05-17 15:23:40Z mthomas $");

#include "probeconfscan.h"
#include "probeconfparse.h"


/* TYPEDEFS AND DEFINES */

typedef struct pcscan_file_st {
    YY_BUFFER_STATE state;
    char           *name;
    FILE           *fp;
    int             line;
} pcscan_file_t;


/* EXPORTED VARIABLES */

/* Global error count for return status of skpcParse */
int pcscan_errors;

/* keyword we read; for printing messages in the parser. */
char pcscan_clause[128];

int (*extra_sensor_verify_fn)(skpc_sensor_t *sensor) = NULL;


/* LOCAL FUNCTION PROTOTYPES */

static int stash(int tok);
static void err_bad_line(int is_id);
static void err_include_arg(void);
static char *get_name(const char *s, int c);
static void filter_start(char unless_when);
static int filter_set_type(char filter_type, char list_type);

/* support for "include" */
static pcscan_file_t pcscan_stack[PCSCAN_MAX_INCLUDE_DEPTH];

/* next stack position */
static int pcscan_stack_depth = 0;

/* current pointer into pcscan_stack[] */
static pcscan_file_t *pcscan_file = NULL;

/* local buffer for reading quoted strings */
#define BUF_SIZE 2048
static char pcscan_buf[BUF_SIZE];
static char *pcscan_buf_end = pcscan_buf + BUF_SIZE - 1;
static char *pcscan_buf_ptr;

/* Check that we're not overflowing the buffer */
#define STRING_CHECK                            \
    if ( pcscan_buf_ptr >= pcscan_buf_end ) {   \
        skpcParseErr("String too long");        \
        BEGIN(ST_ERR);                          \
        return ERR_STR_TOO_LONG;                \
    }

SK_DIAGNOSTIC_IGNORE_PUSH("-Wwrite-strings")

#line 1194 "probeconfscan.c"
#define YY_NO_INPUT 1
#line 127 "probeconfscan.l"
    /* %option noyyget_extra noyyset_extra noyyget_leng noyyget_text */
    /* %option noyyget_lineno noyyset_lineno noyyget_in noyyset_in */
    /* %option noyyget_out noyyset_out noyyget_lval noyyset_lval */
    /* %option noyyget_lloc noyyset_lloc noyyget_debug noyyset_debug */
    /* ST_ARGS state says we have read a keyword and are parsing the
     * arguments */

    /* ST_FILTER state is used to read the token following a
     * 'discard-unless' or 'discard-when' key word */

    /* ST_ERR state is for an unrecognized keyword at start of line;
     * reads to EOL.  Does not return any token to parser */

    /* ST_ARG_ERR state is for an unrecognized keyword within a
     * statement---that is, after having returned a token to the
     * parser.  It reads to EOL and returns an EOL to the parser so
     * that the parser can put itself into a good state. */

    /* ST_STRING state is for processing quoted strings */

    /* ST_NEWLINE state is used when a newline is read.  One purpose
     * is to delay incrementing the line count until after the parser
     * has processed the line---so errors are reported on correct
     * line.  A second purpose is to detect when the file does not
     * have a final newline. */

    /* ST_IGNORE_SENSOR state is used to ignore the sensor statements
     * (when parsing a file for flowcap) */

    /* basic character classes */
    /* An id must match keywords and sensor names as well as
     * pathnames, hostnames, and IP addresses.  Allow any
     * non-whitespace printable character other than " ' # , */
    /* whitespace; we ignore it */
    /* comment; ignore */
    /* newline, maybe preceded by whitespace */
    /* end of line, maybe preceded by comment; increment line count */
#line 1234 "probeconfscan.c"

#define INITIAL 0
#define ST_ARGS 1
#define ST_FILTER 2
#define ST_ERR 3
#define ST_ARG_ERR 4
#define ST_STRING 5
#define ST_NEWLINE 6
#define ST_IGNORE_SENSOR 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 206 "probeconfscan.l"


    /* ST_NEWLINE state: increment the line-count for the newline we
     * saw at the end of the previous statement.  Stay in the
     * ST_NEWLINE state if this line contains a comment or whitespace.
     * Otherwise, go into the INITIAL state by reading a character
     * then putting it back. */

#line 1445 "probeconfscan.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 479 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 478 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 214 "probeconfscan.l"
{ ++pcscan_file->line; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 215 "probeconfscan.l"
{ yyless(0); ++pcscan_file->line;
                                          BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 218 "probeconfscan.l"
;
	YY_BREAK
/* handle comment at end of file with no trailing newline */
case 4:
YY_RULE_SETUP
#line 222 "probeconfscan.l"
{ BEGIN(ST_NEWLINE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 223 "probeconfscan.l"
{ BEGIN(ST_ERR); }
	YY_BREAK
/* read first keyword on a line */
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 227 "probeconfscan.l"
{ BEGIN(ST_NEWLINE);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 229 "probeconfscan.l"
{ yylval.string = get_name(yytext,'-');
                                          return stash(NET_NAME_INTERFACE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 232 "probeconfscan.l"
{ yylval.string = get_name(yytext,'-');
                                          return stash(NET_NAME_IPBLOCK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 235 "probeconfscan.l"
{ yylval.string = get_name(yytext,'-');
                                          return stash(NET_NAME_IPSET); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 238 "probeconfscan.l"
{ yylval.string = get_name(yytext,'-');
                                          return stash(PROBES); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 241 "probeconfscan.l"
{ return stash(ACCEPT_FROM_HOST_T); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 242 "probeconfscan.l"
{ yylval.net_dir = SKPC_DIR_DST;
                                          return stash(NET_DIRECTION);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 244 "probeconfscan.l"
{ return stash(END_GROUP_T); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 245 "probeconfscan.l"
{ return stash(END_PROBE_T); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 246 "probeconfscan.l"
{ return stash(END_SENSOR_T); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 247 "probeconfscan.l"
{ return stash(GROUP_T); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 248 "probeconfscan.l"
{ return stash(INCLUDE_T); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 249 "probeconfscan.l"
{ err_include_arg();BEGIN(ST_NEWLINE);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 250 "probeconfscan.l"
{ return stash(INTERFACES_T); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 251 "probeconfscan.l"
{ return stash(INTERFACE_VALUES_T); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 252 "probeconfscan.l"
{ return stash(IPBLOCKS_T); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 253 "probeconfscan.l"
{ return stash(IPSETS_T); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 254 "probeconfscan.l"
{ return stash(ISP_IP_T); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 255 "probeconfscan.l"
{ return stash(LISTEN_AS_HOST_T); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 256 "probeconfscan.l"
{ return stash(LISTEN_ON_PORT_T); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 257 "probeconfscan.l"
{ return stash(LISTEN_ON_USOCKET_T);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 258 "probeconfscan.l"
{ return stash(LISTEN_ON_USOCKET_T);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 259 "probeconfscan.l"
{ return stash(LOG_FLAGS_T); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 260 "probeconfscan.l"
{ return stash(POLL_DIRECTORY_T); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 261 "probeconfscan.l"
{ return stash(PRIORITY_T); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 262 "probeconfscan.l"
{ return stash(PROBE_T); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 263 "probeconfscan.l"
{ return stash(PROTOCOL_T); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 264 "probeconfscan.l"
{ return stash(QUIRKS_T); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 265 "probeconfscan.l"
{ return stash(READ_FROM_FILE_T); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 266 "probeconfscan.l"
{ yylval.net_dir = SKPC_DIR_SRC;
                                          return stash(NET_DIRECTION); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 268 "probeconfscan.l"
{ if (extra_sensor_verify_fn) {
                                              return stash(SENSOR_T);
                                          } else {
                                              BEGIN(ST_IGNORE_SENSOR);
                                        } }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 274 "probeconfscan.l"
{ yyless(0); BEGIN(ST_ERR); }
	YY_BREAK
/* go into the ST_FILTER state */
case 38:
YY_RULE_SETUP
#line 278 "probeconfscan.l"
{ filter_start('u'); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 279 "probeconfscan.l"
{ filter_start('w'); }
	YY_BREAK
/* ST_FILTER state: handle the second keyword for "discard-when"
     * and "discard-unless" */
case 40:
YY_RULE_SETUP
#line 284 "probeconfscan.l"
{ return filter_set_type('a', 'n'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 285 "probeconfscan.l"
{ return filter_set_type('d', 'n'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 286 "probeconfscan.l"
{ return filter_set_type('s', 'n'); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 288 "probeconfscan.l"
{ return filter_set_type('a', 'w'); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 289 "probeconfscan.l"
{ return filter_set_type('d', 'w'); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 290 "probeconfscan.l"
{ return filter_set_type('s', 'w'); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 292 "probeconfscan.l"
{ return filter_set_type('a', 's'); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 293 "probeconfscan.l"
{ return filter_set_type('d', 's'); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 294 "probeconfscan.l"
{ return filter_set_type('s', 's'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 296 "probeconfscan.l"
{ yyless(0);
                                          filter_set_type('-', '-');
                                          BEGIN(ST_ERR); }
	YY_BREAK
/* ST_ARGS state: handle text after initial keyword */
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 303 "probeconfscan.l"
{ BEGIN(ST_NEWLINE); return EOL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 305 "probeconfscan.l"
{ return REMAINDER_T; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 307 "probeconfscan.l"
{ yylval.string = strdup(yytext);
                                          return ID; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 310 "probeconfscan.l"
{ BEGIN(ST_STRING);
                                          pcscan_buf_ptr = pcscan_buf; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 313 "probeconfscan.l"
{ return COMMA; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 315 "probeconfscan.l"
{ yyless(0); BEGIN(ST_ARG_ERR); }
	YY_BREAK
/* handle errors */
case 56:
YY_RULE_SETUP
#line 320 "probeconfscan.l"
{ err_bad_line(1); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 322 "probeconfscan.l"
{ err_bad_line(0); }
	YY_BREAK
/* return EOL so the parser can throw away its current state */
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 326 "probeconfscan.l"
{ BEGIN(ST_NEWLINE); return EOL; }
	YY_BREAK
/* ST_IGNORE_SENSOR state: ignore everything until we reach the
     * "end sensor" line. */
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 332 "probeconfscan.l"
{ BEGIN(ST_NEWLINE);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 333 "probeconfscan.l"
{ BEGIN(ST_ERR); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 334 "probeconfscan.l"
{ ++pcscan_file->line; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 335 "probeconfscan.l"
;
	YY_BREAK
/* ST_STRING state: Accepts the remainder of a quoted string
     * (after the initial quote) and returns the value.  This is
     * pretty much equivalent to quoted strings in C. */
case 63:
YY_RULE_SETUP
#line 342 "probeconfscan.l"
{ BEGIN(ST_ARGS);
                          STRING_CHECK;
                          *pcscan_buf_ptr = '\0';
                          yylval.string = strdup(pcscan_buf);
                          return QUOTED_STRING; }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 348 "probeconfscan.l"
{ BEGIN(ST_NEWLINE);
                          skpcParseErr("Quoted string missing closing quote");
                          return EOL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 352 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\n'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 353 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\t'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 354 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\r'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 355 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\b'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 356 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\f'; }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 357 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = '\n'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 358 "probeconfscan.l"
{ STRING_CHECK; *pcscan_buf_ptr++ = yytext[1]; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 360 "probeconfscan.l"
{ if ((pcscan_buf_ptr + yyleng) > pcscan_buf_end ) {
                              BEGIN(ST_ERR);
                              return ERR_STR_TOO_LONG;
                          }
                          memcpy(pcscan_buf_ptr, yytext, yyleng);
                          pcscan_buf_ptr += yyleng; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 367 "probeconfscan.l"
ECHO;
	YY_BREAK
#line 1911 "probeconfscan.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ST_ARGS):
case YY_STATE_EOF(ST_FILTER):
case YY_STATE_EOF(ST_ERR):
case YY_STATE_EOF(ST_ARG_ERR):
case YY_STATE_EOF(ST_STRING):
case YY_STATE_EOF(ST_NEWLINE):
case YY_STATE_EOF(ST_IGNORE_SENSOR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 479 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 479 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 478);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current token.
 * 
 */

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 367 "probeconfscan.l"


SK_DIAGNOSTIC_IGNORE_POP("-Wwrite-strings")

int
yywrap(
    void)
{
    switch (YY_START) {
      case ST_NEWLINE:
        /* this is what we expect */
        break;
      case ST_IGNORE_SENSOR:
        skpcParseErr("Missing \"end sensor\" or final newline");
        break;
      case ST_STRING:
        skpcParseErr("Quoted string missing closing quote");
        break;
      default:
        skpcParseErr("Missing final newline or"
                     " incomplete statement at end-of-file");
        BEGIN(ST_NEWLINE);
        break;
    }
    return skpcParseIncludePop();
}


/*
 *  stash(int)
 *
 *      Stash the current keyword (using the yyleng and yytext
 *      globals), put us into a ST_ARGS start-state, and return the
 *      value we were passed.
 */
static int
stash(
    int                 tok)
{
    /* make certain the keyword fits in our buffer */
    assert(yyleng < ((int)sizeof(pcscan_clause)));

    /* copy it in */
    strncpy(pcscan_clause, yytext, sizeof(pcscan_clause) - 1);

    /* we're processing the arguments */
    BEGIN(ST_ARGS);

    /* return whatever we were passed */
    return tok;
}


/*
 *  string = get_name(input_string, c);
 *
 *    Allocate and return a copy of 'input_string' up to (but not
 *    including) the character 'c'.  If 'input_string' does not
 *    contain 'c', return a copy of the entire string.
 */
static char *
get_name(
    const char         *s,
    int                 c)
{
    const char *cp = strrchr(s, c);
    char *sp;

    if (cp == NULL) {
        return strdup(s);
    }
    sp = (char*)malloc(1 + (cp - s));
    if (sp) {
        strncpy(sp, s, (cp - s));
        sp[(cp - s)] = '\0';
    }
    return sp;
}


/*
 *  filter_start(unless_when);
 *
 *    Handle the "discard-when" and "discard-unless" keywords, and
 *    stash the keyword.  'unless_when' should be 'u' if this is a
 *    "discard-unless" keyword, and a 'w' for "discard-when".  Prepare
 *    to handle the next keyword describing what to
 *    discard-unless/when and the type of data.
 */
static void
filter_start(
    char                unless_when)
{
    /* copy keyword into the pcscan_clause */
    strncpy(pcscan_clause, yytext, sizeof(pcscan_clause) - 1);

    /* initialize filter */
    memset(&yylval.filter, 0, sizeof(skpc_filter_t));

    switch (unless_when) {
      case 'u':
        yylval.filter.f_discwhen = 0;
        break;
      case 'w':
        yylval.filter.f_discwhen = 1;
        break;
      default:
        skpcParseErr("Invalid unless_when '%c'", unless_when);
        skAbort();
    }

    BEGIN(ST_FILTER);
}


/*
 *  filter_set_type(filter_type, list_type);
 *
 *    Handle the second keyword in a "discard-when" or
 *    "discard-unless" statement.  Append this additional text to the
 *    'pcscan_clause' used to report errors.
 *
 *    'filter_type' specifies the first character of the second
 *    keyword ('a'ny, 'd'estination, 's'source), and it determines the
 *    skpc_filter_type_t.
 *
 *    'list_type' is 'n' for numbers (interfaces), 'w' for wildcards
 *    (ipblocks), and 's' for IPsets.
 *
 *    A 'filter_type' of '-' indicates an error parsing the keyword
 *    following the discard-when/discard-unless statement.
 */
static int
filter_set_type(
    char                filter_type,
    char                list_type)
{
    if ('-' == filter_type) {
        /* invalid keyword */
        skpcParseErr("Missing or invalid type for %s", pcscan_clause);
        return -1;
    }

    /* append text into pcscan_clause */
    strncat(pcscan_clause, " ",
            (sizeof(pcscan_clause) - strlen(pcscan_clause) - 1));
    strncat(pcscan_clause, yytext,
            (sizeof(pcscan_clause) - strlen(pcscan_clause) - 1));

    switch (filter_type) {
      case 'a':
        yylval.filter.f_type = SKPC_FILTER_ANY;
        break;
      case 'd':
        yylval.filter.f_type = SKPC_FILTER_DESTINATION;
        break;
      case 's':
        yylval.filter.f_type = SKPC_FILTER_SOURCE;
        break;
      default:
        skpcParseErr("Invalid filter_type '%c'", filter_type);
        skAbort();
    }
    switch (list_type) {
      case 'n':                 /* interface numbers */
        yylval.filter.f_group_type = SKPC_GROUP_INTERFACE;
        break;
      case 'w':                 /* ipblock wildcards */
        yylval.filter.f_group_type = SKPC_GROUP_IPBLOCK;
        break;
      case 's':                 /* IPset filenames */
        yylval.filter.f_group_type = SKPC_GROUP_IPSET;
        break;
      default:
        skpcParseErr("Invalid list_type '%c'", list_type);
        skAbort();
    }

    /* prepare to grab the interfaces, ipblocks, or IPsets */
    BEGIN(ST_ARGS);
    return FILTER;
}


/*
 *  err_bad_line(is_id);
 *
 *    Called when the scanner reads a bad line of input.  This
 *    function prints an error and increases the global error count.
 *
 *    If 'is_id' is 0, we have a single uknown character; otherwise we
 *    have a bad keyword.  At this point yytext holds the entire bad
 *    line.
 */
static void
err_bad_line(
    int                 is_id)
{
    size_t i;

    /* Make sure the parser lets the application know that things failed. */
    ++pcscan_errors;

    /* Handle a bad character; this is easy */
    if (is_id == 0) {
        skpcParseErr("Unexpected character '%c'", yytext[0]);
        return;
    }

    /* Handle a bad keyword.  Copy the first keyword into
     * pcscan_clause[] so we can print it. */
    for (i = 0; i < sizeof(pcscan_clause)-1; ++i) {
        /* This switch has the same character classes as our {idchar}. */
        switch (yytext[i]) {
          case '\0':
            goto END_WORD;
          case '-':
          case '.':
          case '_':
          case '/':
            pcscan_clause[i] = yytext[i];
            break;
          default:
            if (isalnum((int)yytext[i])) {
                pcscan_clause[i] = yytext[i];
            } else {
                goto END_WORD;
            }
            break;
        }
    }
  END_WORD:
    pcscan_clause[i] = '\0';

    skpcParseErr("Unrecognized keyword '%s'", pcscan_clause);
}


/*
 *  err_include_arg();
 *
 *    Print a message about the argument to include statement.
 */
static void
err_include_arg(
    void)
{
    /* Make sure the parser lets the application know that things failed. */
    ++pcscan_errors;

    skpcParseErr("Argument to include must be in \"double quotes\"");
}


#ifndef TEST_PRINTF_FORMATS
int
skpcParseErr(
    const char         *fmt,
    ...)
{
    va_list args;

    va_start(args, fmt);
    if (pcscan_file != NULL && pcscan_file->name != NULL) {
        fprintf(stderr, "%s: Error while parsing file %s at line %d:\n\t",
                skAppName(), pcscan_file->name, pcscan_file->line);
    } else {
        fprintf(stderr, "%s: Error during parsing [no current file]:\n\t",
                skAppName());
    }
    vfprintf(stderr, fmt, args);
    fprintf(stderr, "\n");
    va_end(args);
    return 0;
}
#endif  /* TEST_PRINTF_FORMATS */


static int
skpcParseOpenFile(
    char               *filename)
{
    pcscan_file_t *new_file;
    const char *action_name =
        ((pcscan_stack_depth == 0) ? "read sensor-config" : "include");

    if (filename == NULL) {
        goto ERROR;
    }

    if (!skFileExists(filename)) {
        if (0 == pcscan_stack_depth) {
            skAppPrintErr(("Cannot %s '%s': "
                           "File does not exist or is not a regular file"),
                          action_name, filename);
        } else {
            skpcParseErr(("Cannot %s '%s': "
                          "File does not exist or is not a regular file"),
                         action_name, filename);
        }
        goto ERROR;
    }

    if (pcscan_stack_depth >= PCSCAN_MAX_INCLUDE_DEPTH) {
        skpcParseErr("Cannot include file '%s': includes nested too deeply",
                     filename);
        goto ERROR;
    }

    new_file = &pcscan_stack[pcscan_stack_depth];
    new_file->name = filename;
    new_file->line = 0;

    /* open the file */
    new_file->fp = fopen(new_file->name, "r");
    if (!new_file->fp) {
        skpcParseErr("Cannot %s '%s': %s",
                     action_name, filename, strerror(errno));
        goto ERROR;
    }

    /* set up scanner */
    new_file->state = yy_create_buffer(new_file->fp, YY_BUF_SIZE);
    yy_switch_to_buffer(new_file->state);

    /* success */
    pcscan_file = new_file;
    ++pcscan_stack_depth;
    BEGIN(ST_NEWLINE);

    return 0;

  ERROR:
    if (filename) {
        free(filename);
    }
    return -1;
}


int
skpcParseIncludePop(
    void)
{
    if (pcscan_stack_depth == 0) {
        return 1;
    }

    /* free current state */
    yy_delete_buffer(YY_CURRENT_BUFFER);
    fclose(pcscan_file->fp);
    free(pcscan_file->name);

    /* pop to previous state; if no more states, we're done */
    --pcscan_stack_depth;
    if (pcscan_stack_depth == 0) {
        pcscan_file = NULL;
        return 1;
    }

    pcscan_file = &(pcscan_stack[pcscan_stack_depth-1]);
    yy_switch_to_buffer(pcscan_file->state);

    /* let processing continue */
    return 0;
}


int
skpcParseIncludePush(
    char               *filename)
{
    return skpcParseOpenFile(filename);
}


int
skpcParse(
    const char         *filename,
    int               (*site_verify_sensor_fn)(skpc_sensor_t *sensor))
{
    /* store the site-specific sensor-verify function */
    extra_sensor_verify_fn = site_verify_sensor_fn;

    /* clear the error count */
    pcscan_errors = 0;

    /* initialize the include stack */
    pcscan_stack_depth = 0;

    /* send in a copy so we can free it */
    if (skpcParseOpenFile(strdup(filename))) {
        return -1;
    }

    /* parse */
    (void)yyparse();

    /* return non-zero if we had errors */
    if (pcscan_errors > 0) {
        return -1;
    }

    return 0;
}


/*
** Local Variables:
** mode:c
** indent-tabs-mode:nil
** c-basic-offset:4
** End:
*/

